### ISSUE TITLE
FSInfo creates a DFSClient each time the API is called for older versions of hadoop

### ISSUE THREAD

**Issue by brockn** [brockn/hdfs-nfs-proxy#10]
Using the proxy with older hadoops will cause many thread to be in the following state:

"pool-1-thread-7" prio=10 tid=0x000000004fd8a000 nid=0x6b0 in Object.wait() [0x0000000042598000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:485)
        at org.apache.hadoop.ipc.Client.call(Client.java:1052)
        - locked <0x00000000f5fe7120> (a org.apache.hadoop.ipc.Client$Call)
        at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:225)
        at $Proxy1.getProtocolVersion(Unknown Source)
        at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:396)
        at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:379)
        at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:119)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:238)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:203)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:193)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:184)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.FSInfo.getUsed(FSInfo.java:61)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.SpaceUsedHandler.get(SpaceUsedHandler.java:38)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.SpaceUsedHandler.get(SpaceUsedHandler.java:1)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.Attribute.getAttrs(Attribute.java:175)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.handlers.GETATTRHandler.doHandle(GETATTRHandler.java:54)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.handlers.GETATTRHandler.doHandle(GETATTRHandler.java:1)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.handlers.OperationRequestHandler.handle(OperationRequestHandler.java:57)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4Handler$1.run(NFS4Handler.java:148)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4Handler$1.run(NFS4Handler.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:396)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1083)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4Handler.process(NFS4Handler.java:136)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4Handler.process(NFS4Handler.java:1)
        at com.cloudera.hadoop.hdfs.nfs.rpc.ClientWorker$ClientTask.run(ClientWorker.java:379)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)

**Comment by brockn** [comment]
We should probably just make FSInfo non-static and then use a thread local to store the DFSclient.

**Comment by brockn** [comment]
Resolved in async-writes branch which will be merged.
