### ISSUE TITLE
Mount fails from RHEL 6.3

### ISSUE THREAD

**Issue by brockn** [brockn/hdfs-nfs-proxy#11]
```
012-10-01 14:21:40,886 (pool-1-thread-4) [WARN - com.cloudera.hadoop.hdfs.nfs.nfs4.requests.CompoundRequest.read(CompoundRequest.java:54)] Dropping request with id 0: [com.cloudera.hadoop.hdfs.nfs.nfs4.requests.PUTFHRequest@477a1767, com.cloudera.hadoop.hdfs.nfs.nfs4.requests.SETATTRRequest@20968fda]
2012-10-01 14:21:40,887 (pool-1-thread-4) [ERROR - com.cloudera.hadoop.hdfs.nfs.rpc.ClientWorker$ClientTask.run(ClientWorker.java:391)] 0x7ffffffa Error from client /10.0.1.102 xid = -238199906
java.lang.UnsupportedOperationException: NFS ID 0
    at com.cloudera.hadoop.hdfs.nfs.nfs4.requests.CompoundRequest.read(CompoundRequest.java:55)
    at com.cloudera.hadoop.hdfs.nfs.rpc.ClientWorker$ClientTask.run(ClientWorker.java:373)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
```

**Comment by brockn** [comment]
Turns out this was not a mounting issue but a SETATTR right after mounting. It's flags were empty which we were not handling appropriately.
