### ISSUE TITLE
Can't mount NFS export: Access denied for user root. Superuser privilege is required

### ISSUE THREAD

**Issue by mtippmann** [brockn/hdfs-nfs-proxy#14]
I have the same issue like #5  2)

I can confirm this with the latest git version and Hadoop 1.0.4 (not CDH, used `-Phadoop1`) on Ubuntu 12.04: 

The mount fails with: 

```
 mount.nfs4: Remote I/O error
```

some Details from the error log:

``` Java
12/11/30 00:32:17 INFO state.HDFSState: Writing temp files to [/tmp/hdfs-nfs-proxy/tmp]
12/11/30 00:32:17 INFO rpc.RPCServer: class com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4Handler created server ServerSocket[addr=0.0.0.0/0.0.0.0,port=0,localport=2051] on 2051
12/11/30 00:32:51 INFO rpc.RPCServer: class com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4Handler got client localhost:862
12/11/30 00:32:51 ERROR nfs.NetUtils: Unable to find the domain the server is running on. Please report.
canonicalHostName = localhost
hostname = localhost
isLoopback = true
hostAdddress = 127.0.0.1
12/11/30 00:32:51 ERROR nfs.NetUtils: Unable to find the domain the server is running on. Please report.
canonicalHostName = localhost
hostname = localhost
isLoopback = true
hostAdddress = 127.0.0.1
12/11/30 00:32:51 WARN handlers.OperationRequestHandler: 0x7ffffffa Error for client localhost/127.0.0.1 and GETATTRResponse
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.FSInfo.getObject(FSInfo.java:83)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.FSInfo.getUsed(FSInfo.java:129)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.SpaceUsedHandler.get(SpaceUsedHandler.java:37)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.SpaceUsedHandler.get(SpaceUsedHandler.java:31)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.Attribute.getAttrs(Attribute.java:122)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.handlers.GETATTRHandler.doHandle(GETATTRHandler.java:60)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.handlers.GETATTRHandler.doHandle(GETATTRHandler.java:41)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.handlers.OperationRequestHandler.handle(OperationRequestHandler.java:81)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4AsyncFuture.doMakeProgress(NFS4AsyncFuture.java:78)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4AsyncFuture$1.run(NFS4AsyncFuture.java:98)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4AsyncFuture$1.run(NFS4AsyncFuture.java:95)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1121)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4AsyncFuture.makeProgress(NFS4AsyncFuture.java:95)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.AsyncTaskExecutor$TaskRunnable.run(AsyncTaskExecutor.java:103)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.FSInfo.getObject(FSInfo.java:81)
    ... 21 more
Caused by: org.apache.hadoop.ipc.RemoteException: org.apache.hadoop.security.AccessControlException: Access denied for user root. Superuser privilege is required
    at org.apache.hadoop.hdfs.server.namenode.PermissionChecker.checkSuperuserPrivilege(PermissionChecker.java:69)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkSuperuserPrivilege(FSNamesystem.java:5198)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getStats(FSNamesystem.java:4063)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.getStats(NameNode.java:853)
    at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:563)
    at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1388)
    at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1384)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1121)
    at org.apache.hadoop.ipc.Server$Handler.run(Server.java:1382)

    at org.apache.hadoop.ipc.Client.call(Client.java:1070)
    at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:225)
    at $Proxy1.getStats(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:82)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:59)
    at $Proxy1.getStats(Unknown Source)
    at org.apache.hadoop.hdfs.DFSClient.totalRawUsed(DFSClient.java:1081)
    ... 26 more
12/11/30 00:32:51 WARN nfs4.NFS4AsyncFuture: 0x7ffffffa Quitting due to 10006 on GETATTRRequest for root
12/11/30 00:32:51 INFO rpc.ClientInputHandler: 0x7ffffffa fe757077 Writing CompoundResponse to localhost:862
12/11/30 00:32:51 INFO rpc.ClientInputHandler: 0x7ffffffa Shutdown worker for client localhost:862
12/11/30 00:32:51 INFO rpc.RPCServer: class com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4Handler got client <host omitted>:906
12/11/30 00:32:51 WARN handlers.OperationRequestHandler: 0x7ffffff5 Error for client <hostname omitted> and GETATTRResponse
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.FSInfo.getObject(FSInfo.java:83)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.FSInfo.getUsed(FSInfo.java:129)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.SpaceUsedHandler.get(SpaceUsedHandler.java:37)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.SpaceUsedHandler.get(SpaceUsedHandler.java:31)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.Attribute.getAttrs(Attribute.java:122)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.handlers.GETATTRHandler.doHandle(GETATTRHandler.java:60)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.handlers.GETATTRHandler.doHandle(GETATTRHandler.java:41)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.handlers.OperationRequestHandler.handle(OperationRequestHandler.java:81)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4AsyncFuture.doMakeProgress(NFS4AsyncFuture.java:78)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4AsyncFuture$1.run(NFS4AsyncFuture.java:98)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4AsyncFuture$1.run(NFS4AsyncFuture.java:95)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1121)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4AsyncFuture.makeProgress(NFS4AsyncFuture.java:95)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.AsyncTaskExecutor$TaskRunnable.run(AsyncTaskExecutor.java:103)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.FSInfo.getObject(FSInfo.java:81)
    ... 21 more
Caused by: org.apache.hadoop.ipc.RemoteException: org.apache.hadoop.security.AccessControlException: Access denied for user root. Superuser privilege is required
    at org.apache.hadoop.hdfs.server.namenode.PermissionChecker.checkSuperuserPrivilege(PermissionChecker.java:69)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkSuperuserPrivilege(FSNamesystem.java:5198)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getStats(FSNamesystem.java:4063)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.getStats(NameNode.java:853)
    at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:563)
    at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1388)
    at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1384)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1121)
    at org.apache.hadoop.ipc.Server$Handler.run(Server.java:1382)

    at org.apache.hadoop.ipc.Client.call(Client.java:1070)
    at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:225)
    at $Proxy1.getStats(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:82)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:59)
    at $Proxy1.getStats(Unknown Source)
    at org.apache.hadoop.hdfs.DFSClient.totalRawUsed(DFSClient.java:1081)
    ... 26 more
12/11/30 00:32:51 WARN nfs4.NFS4AsyncFuture: 0x7ffffff5 Quitting due to 10006 on GETATTRRequest for root
12/11/30 00:32:51 INFO rpc.ClientInputHandler: 0x7ffffff5 234bb914 Writing CompoundResponse to <host omitted>:906
12/11/30 00:32:51 INFO rpc.ClientInputHandler: 0x7ffffff5 Shutdown worker for client <hostname omitted>:906
```

I've tested it locally with user `hadoop` and my local user. I've also tested it between different hosts. 

core-site.xml:

``` xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

<configuration>
  <property>
    <name>hadoop.tmp.dir</name>
    <value>/tmp</value>
  </property>
  <property>
    <name>fs.checkpoint.dir</name>
    <value>/mnt/storage1/hadoop/tmp/dfs/namesecondary,/mnt/storage2/hadoop/tmp/dfs/namesecondary,/mnt/storage3/hadoop/tmp/dfs/namesecondary</value>
  </property>
  <property>
    <name>fs.default.name</name>
    <value>hdfs://<host omitted>:8020</value>
  </property>
  <property>
    <name>fs.trash.interval</name>
    <value>1440</value>
  </property>
</configuration>
```

hdfs-nfs-site.xml: 

``` xml
$ cat hdfs-nfs-site.xml 
<?xml version="1.0" encoding="UTF-8"?>

<configuration>
  <property>
    <name>hdfs.nfs.data.dir</name>
    <value>/tmp/hdfs-nfs-proxy/data</value>
    <!-- Persistent location for nfs proxy to write important data -->
  </property>
  <property>
    <name>hdfs.nfs.temp.dirs</name>
    <value>/tmp/hdfs-nfs-proxy/tmp</value>
    <!-- CSV of temp directories to write pending writes -->
  </property>
  <property>
    <name>hdfs.nfs.security.flavor</name>
    <value>unix</value>
    <!-- Security flavor, if set to kerberos (krb5p) additional properties need to be configured -->
  </property>
  <property>
    <name>hdfs.nfs.security.allowed.hosts</name>
    <value>
      localhost.localdomain rw
      * ro
    </value>
    <!--
        This is a new line seperated list of any of the following:
        1) * - which exports filesystem to all hosts
        2) hostnames or ip addresses
        3) CIDR such as 192.168.0.0/255.255.252.0 or 192.168.0.0/22
        4) Java Regex match host or ip such as: 192.168.0.[0-9]+ or [a-z]+.b.com

        followed by either ro for read-only access or rw for read write access
    -->
  </property>
</configuration>
```

I don't have time to dig further into the code, any hints how to resolve this are welcome. I don't have much experience with either NFSv4 nor Hadoop HDFS.

**Comment by brockn** [comment]
With hadoop1 I think you need to run the daemon as the same user who is running hdfs. Note that for hdfs, root is not the super user.

**Comment by brockn** [comment]
Also, 99.99% of the testing has been down with CDH4 so I personally would use that if you are planning on using the proxy.

**Comment by mtippmann** [comment]
Hi, thanks for the quick response. I've run it using the `hadoop` user directly on the NameNode. There is no hdfs user in the stock Hadoop distribution - so `hadoop` should be the superuser. 

Unfortunately running CDH4 is no option at the moment (not my decision). 

I'm trying to debug the issue a little bit more and respond if I know more! Thanks!

**Comment by brockn** [comment]
OK, I'd love to help you more but being only one person I only have so much time to test and CDH4 is what I use... I will happily take patches for hadoop 1.X.

**Comment by mtippmann** [comment]
Thanks for you effort and this great software! I solved my problem - but for now in an ugly way - I hope I find the time over the next days to find the cause for the problem and would issue an patch - for now this helped me (I guess there are probably ugly side effects, but I only need read access right now) 

By hardcoding `getUser()` in SessionSecurityHandlerSystem.java I got it working:

``` Java
  public String getUser() throws NFS4Exception {
    try {
      //String user = "hadoop"; //mUserIDMapper.getUserForUID(mCredentialsSystem.getUID(), ANONYMOUS_USERNAME);
      return "hadoop";
  }
```

**Comment by brockn** [comment]
Oh yeah I think I remember now. Hadoop 1 requires that root be mapped to hdfs/hadoop. We should probably have a configuration option like map.root.to.user and then have it default to root. Then ppl using hadoop1 can set it to hadoop.

**Comment by brockn** [comment]
Moved here https://github.com/cloudera/hdfs-nfs-proxy/issues/2
